ALTER TABLE agent_tools
    ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS parameters JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS endpoint_url TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS http_method TEXT DEFAULT 'GET',
    ADD COLUMN IF NOT EXISTS headers JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS auth_type TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS auth_config JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
    ADD COLUMN IF NOT EXISTS timeout_sec INT DEFAULT 30,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
