# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """WorkerService is the gRPC service that Python workers connect to.
    Workers maintain a persistent bidirectional stream for task dispatch.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TaskStream = channel.stream_stream(
                '/worker.v1.WorkerService/TaskStream',
                request_serializer=worker__pb2.WorkerMessage.SerializeToString,
                response_deserializer=worker__pb2.ServerMessage.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/worker.v1.WorkerService/Heartbeat',
                request_serializer=worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """WorkerService is the gRPC service that Python workers connect to.
    Workers maintain a persistent bidirectional stream for task dispatch.
    """

    def TaskStream(self, request_iterator, context):
        """TaskStream is a bidirectional stream: workers register, receive tasks, and send results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat is a lightweight health ping from workers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TaskStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=worker__pb2.WorkerMessage.FromString,
                    response_serializer=worker__pb2.ServerMessage.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=worker__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.v1.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.v1.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """WorkerService is the gRPC service that Python workers connect to.
    Workers maintain a persistent bidirectional stream for task dispatch.
    """

    @staticmethod
    def TaskStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/worker.v1.WorkerService/TaskStream',
            worker__pb2.WorkerMessage.SerializeToString,
            worker__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.v1.WorkerService/Heartbeat',
            worker__pb2.HeartbeatRequest.SerializeToString,
            worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
