// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkerMessage is sent from the worker to the server.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_TaskResponse
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *RegisterWorker {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResponse() *TaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskResponse); ok {
			return x.TaskResponse
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *RegisterWorker `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_TaskResponse struct {
	TaskResponse *TaskResponse `protobuf:"bytes,2,opt,name=task_response,json=taskResponse,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskResponse) isWorkerMessage_Payload() {}

// ServerMessage is sent from the server to the worker.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_TaskRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetTaskRequest() *TaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TaskRequest); ok {
			return x.TaskRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_TaskRequest struct {
	TaskRequest *TaskRequest `protobuf:"bytes,2,opt,name=task_request,json=taskRequest,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_TaskRequest) isServerMessage_Payload() {}

// RegisterWorker is the first message a worker sends to identify itself.
type RegisterWorker struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	MaxConcurrent      int32                  `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	SupportedProviders []string               `protobuf:"bytes,3,rep,name=supported_providers,json=supportedProviders,proto3" json:"supported_providers,omitempty"` // e.g., ["openai", "anthropic", "ollama"]
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterWorker) Reset() {
	*x = RegisterWorker{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorker) ProtoMessage() {}

func (x *RegisterWorker) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorker.ProtoReflect.Descriptor instead.
func (*RegisterWorker) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWorker) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorker) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *RegisterWorker) GetSupportedProviders() []string {
	if x != nil {
		return x.SupportedProviders
	}
	return nil
}

// RegisterAck is sent by the server to confirm registration.
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ToolDefinition describes an external tool that an agent can invoke during LLM execution.
type ToolDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson   string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`   // JSON Schema for tool parameters
	EndpointUrl      string                 `protobuf:"bytes,4,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`            // HTTP endpoint to call
	HttpMethod       string                 `protobuf:"bytes,5,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`               // GET, POST, PUT, DELETE
	HeadersJson      string                 `protobuf:"bytes,6,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`            // JSON: {"Authorization": "Bearer ..."}
	AuthType         string                 `protobuf:"bytes,7,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`                     // "", "bearer", "api_key"
	AuthConfigJson   string                 `protobuf:"bytes,8,opt,name=auth_config_json,json=authConfigJson,proto3" json:"auth_config_json,omitempty"` // JSON: {"token": "..."} or {"key": "...", "header": "X-Api-Key"}
	TimeoutSec       int32                  `protobuf:"varint,9,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	Version          string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	Category         string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	ToolType         string                 `protobuf:"bytes,12,opt,name=tool_type,json=toolType,proto3" json:"tool_type,omitempty"` // "builtin" | "http"
	OutputSchemaJson string                 `protobuf:"bytes,13,opt,name=output_schema_json,json=outputSchemaJson,proto3" json:"output_schema_json,omitempty"`
	DependsOn        []string               `protobuf:"bytes,14,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`                // names of tools that must execute before this one
	MaxChainDepth    int32                  `protobuf:"varint,15,opt,name=max_chain_depth,json=maxChainDepth,proto3" json:"max_chain_depth,omitempty"` // max dependency depth (default 5)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

func (x *ToolDefinition) GetEndpointUrl() string {
	if x != nil {
		return x.EndpointUrl
	}
	return ""
}

func (x *ToolDefinition) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *ToolDefinition) GetHeadersJson() string {
	if x != nil {
		return x.HeadersJson
	}
	return ""
}

func (x *ToolDefinition) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *ToolDefinition) GetAuthConfigJson() string {
	if x != nil {
		return x.AuthConfigJson
	}
	return ""
}

func (x *ToolDefinition) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *ToolDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolDefinition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ToolDefinition) GetToolType() string {
	if x != nil {
		return x.ToolType
	}
	return ""
}

func (x *ToolDefinition) GetOutputSchemaJson() string {
	if x != nil {
		return x.OutputSchemaJson
	}
	return ""
}

func (x *ToolDefinition) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *ToolDefinition) GetMaxChainDepth() int32 {
	if x != nil {
		return x.MaxChainDepth
	}
	return 0
}

// ToolContext provides execution context for tools.
type ToolContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`       // trace_id from OpenTelemetry
	PermissionsJson string                 `protobuf:"bytes,5,opt,name=permissions_json,json=permissionsJson,proto3" json:"permissions_json,omitempty"` // JSON with agent permissions
	MetadataJson    string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`          // additional metadata (org_id, channel, etc.)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolContext) Reset() {
	*x = ToolContext{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolContext) ProtoMessage() {}

func (x *ToolContext) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolContext.ProtoReflect.Descriptor instead.
func (*ToolContext) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ToolContext) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ToolContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ToolContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToolContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ToolContext) GetPermissionsJson() string {
	if x != nil {
		return x.PermissionsJson
	}
	return ""
}

func (x *ToolContext) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// ToolCall represents a single invocation of a tool during task processing.
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	ResultJson    string                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolCall) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolCall) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ToolCall) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Attachment represents a file or image sent with a message.
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// TaskRequest is sent from the server to a worker to process a task.
type TaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId           string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OwnerUserId       string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	UserMessage       string                 `protobuf:"bytes,4,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	SystemPrompt      string                 `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`      // Decrypted system prompt
	LlmConfigJson     string                 `protobuf:"bytes,6,opt,name=llm_config_json,json=llmConfigJson,proto3" json:"llm_config_json,omitempty"` // JSON: {"provider":"openai","model":"gpt-4o-mini","temperature":0.7,"max_tokens":1024}
	FromJid           string                 `protobuf:"bytes,7,opt,name=from_jid,json=fromJid,proto3" json:"from_jid,omitempty"`
	AgentJid          string                 `protobuf:"bytes,8,opt,name=agent_jid,json=agentJid,proto3" json:"agent_jid,omitempty"`
	AgentName         string                 `protobuf:"bytes,9,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	MemoryContextJson string                 `protobuf:"bytes,10,opt,name=memory_context_json,json=memoryContextJson,proto3" json:"memory_context_json,omitempty"` // JSON: recent messages + relevant long-term memories
	MemoryConfigJson  string                 `protobuf:"bytes,11,opt,name=memory_config_json,json=memoryConfigJson,proto3" json:"memory_config_json,omitempty"`    // JSON: memory configuration from agent
	Tools             []*ToolDefinition      `protobuf:"bytes,12,rep,name=tools,proto3" json:"tools,omitempty"`                                                    // Available tools for this agent
	Attachments       []*Attachment          `protobuf:"bytes,13,rep,name=attachments,proto3" json:"attachments,omitempty"`                                        // File/image attachments
	ToolContext       *ToolContext           `protobuf:"bytes,15,opt,name=tool_context,json=toolContext,proto3" json:"tool_context,omitempty"`                     // Execution context for tools
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *TaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *TaskRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *TaskRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *TaskRequest) GetLlmConfigJson() string {
	if x != nil {
		return x.LlmConfigJson
	}
	return ""
}

func (x *TaskRequest) GetFromJid() string {
	if x != nil {
		return x.FromJid
	}
	return ""
}

func (x *TaskRequest) GetAgentJid() string {
	if x != nil {
		return x.AgentJid
	}
	return ""
}

func (x *TaskRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *TaskRequest) GetMemoryContextJson() string {
	if x != nil {
		return x.MemoryContextJson
	}
	return ""
}

func (x *TaskRequest) GetMemoryConfigJson() string {
	if x != nil {
		return x.MemoryConfigJson
	}
	return ""
}

func (x *TaskRequest) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *TaskRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *TaskRequest) GetToolContext() *ToolContext {
	if x != nil {
		return x.ToolContext
	}
	return nil
}

// TaskResponse is sent from the worker back to the server with the LLM result.
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ResponseText  string                 `protobuf:"bytes,3,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,6,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Non-empty indicates failure
	NewMemories   []*MemoryEntry         `protobuf:"bytes,8,rep,name=new_memories,json=newMemories,proto3" json:"new_memories,omitempty"`    // New memories to persist (with embeddings from Python)
	ToolsCalled   []*ToolCall            `protobuf:"bytes,9,rep,name=tools_called,json=toolsCalled,proto3" json:"tools_called,omitempty"`    // Tools that were invoked during this task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResponse) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

func (x *TaskResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *TaskResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResponse) GetNewMemories() []*MemoryEntry {
	if x != nil {
		return x.NewMemories
	}
	return nil
}

func (x *TaskResponse) GetToolsCalled() []*ToolCall {
	if x != nil {
		return x.ToolsCalled
	}
	return nil
}

// MemoryEntry represents a memory to be stored, with its embedding vector.
type MemoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`                  // 384-dim vector from sentence-transformers
	MemoryType    string                 `protobuf:"bytes,3,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`       // e.g., "conversation", "fact", "preference"
	MetadataJson  string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"` // Optional JSON metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEntry) Reset() {
	*x = MemoryEntry{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEntry) ProtoMessage() {}

func (x *MemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEntry.ProtoReflect.Descriptor instead.
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *MemoryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryEntry) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *MemoryEntry) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *MemoryEntry) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// HeartbeatRequest is a periodic health check from the worker.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,2,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	MemoryUsageMb int32                  `protobuf:"varint,3,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	AvgLatencyMs  int32                  `protobuf:"varint,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsageMb() int32 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *HeartbeatRequest) GetAvgLatencyMs() int32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

// HeartbeatResponse acknowledges the heartbeat.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\tworker.v1\"\x93\x01\n" +
	"\rWorkerMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.worker.v1.RegisterWorkerH\x00R\bregister\x12>\n" +
	"\rtask_response\x18\x02 \x01(\v2\x17.worker.v1.TaskResponseH\x00R\ftaskResponseB\t\n" +
	"\apayload\"\x94\x01\n" +
	"\rServerMessage\x12;\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x16.worker.v1.RegisterAckH\x00R\vregisterAck\x12;\n" +
	"\ftask_request\x18\x02 \x01(\v2\x16.worker.v1.TaskRequestH\x00R\vtaskRequestB\t\n" +
	"\apayload\"\x85\x01\n" +
	"\x0eRegisterWorker\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05R\rmaxConcurrent\x12/\n" +
	"\x13supported_providers\x18\x03 \x03(\tR\x12supportedProviders\"C\n" +
	"\vRegisterAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x86\x04\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\x12!\n" +
	"\fendpoint_url\x18\x04 \x01(\tR\vendpointUrl\x12\x1f\n" +
	"\vhttp_method\x18\x05 \x01(\tR\n" +
	"httpMethod\x12!\n" +
	"\fheaders_json\x18\x06 \x01(\tR\vheadersJson\x12\x1b\n" +
	"\tauth_type\x18\a \x01(\tR\bauthType\x12(\n" +
	"\x10auth_config_json\x18\b \x01(\tR\x0eauthConfigJson\x12\x1f\n" +
	"\vtimeout_sec\x18\t \x01(\x05R\n" +
	"timeoutSec\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12\x1b\n" +
	"\ttool_type\x18\f \x01(\tR\btoolType\x12,\n" +
	"\x12output_schema_json\x18\r \x01(\tR\x10outputSchemaJson\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x0e \x03(\tR\tdependsOn\x12&\n" +
	"\x0fmax_chain_depth\x18\x0f \x01(\x05R\rmaxChainDepth\"\xd7\x01\n" +
	"\vToolContext\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12)\n" +
	"\x10permissions_json\x18\x05 \x01(\tR\x0fpermissionsJson\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJson\"\xa6\x01\n" +
	"\bToolCall\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"e\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\xb5\x04\n" +
	"\vTaskRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12!\n" +
	"\fuser_message\x18\x04 \x01(\tR\vuserMessage\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12&\n" +
	"\x0fllm_config_json\x18\x06 \x01(\tR\rllmConfigJson\x12\x19\n" +
	"\bfrom_jid\x18\a \x01(\tR\afromJid\x12\x1b\n" +
	"\tagent_jid\x18\b \x01(\tR\bagentJid\x12\x1d\n" +
	"\n" +
	"agent_name\x18\t \x01(\tR\tagentName\x12.\n" +
	"\x13memory_context_json\x18\n" +
	" \x01(\tR\x11memoryContextJson\x12,\n" +
	"\x12memory_config_json\x18\v \x01(\tR\x10memoryConfigJson\x12/\n" +
	"\x05tools\x18\f \x03(\v2\x19.worker.v1.ToolDefinitionR\x05tools\x127\n" +
	"\vattachments\x18\r \x03(\v2\x15.worker.v1.AttachmentR\vattachments\x129\n" +
	"\ftool_context\x18\x0f \x01(\v2\x16.worker.v1.ToolContextR\vtoolContext\"\xe8\x02\n" +
	"\fTaskResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rresponse_text\x18\x03 \x01(\tR\fresponseText\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"model_used\x18\x06 \x01(\tR\tmodelUsed\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\fnew_memories\x18\b \x03(\v2\x16.worker.v1.MemoryEntryR\vnewMemories\x126\n" +
	"\ftools_called\x18\t \x03(\v2\x13.worker.v1.ToolCallR\vtoolsCalled\"\x8b\x01\n" +
	"\vMemoryEntry\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x1f\n" +
	"\vmemory_type\x18\x03 \x01(\tR\n" +
	"memoryType\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\"\xa0\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\factive_tasks\x18\x02 \x01(\x05R\vactiveTasks\x12&\n" +
	"\x0fmemory_usage_mb\x18\x03 \x01(\x05R\rmemoryUsageMb\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x05R\favgLatencyMs\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x9d\x01\n" +
	"\rWorkerService\x12D\n" +
	"\n" +
	"TaskStream\x12\x18.worker.v1.WorkerMessage\x1a\x18.worker.v1.ServerMessage(\x010\x01\x12F\n" +
	"\tHeartbeat\x12\x1b.worker.v1.HeartbeatRequest\x1a\x1c.worker.v1.HeartbeatResponseB8Z6github.com/aiox-platform/aiox/internal/worker/workerpbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_worker_proto_goTypes = []any{
	(*WorkerMessage)(nil),     // 0: worker.v1.WorkerMessage
	(*ServerMessage)(nil),     // 1: worker.v1.ServerMessage
	(*RegisterWorker)(nil),    // 2: worker.v1.RegisterWorker
	(*RegisterAck)(nil),       // 3: worker.v1.RegisterAck
	(*ToolDefinition)(nil),    // 4: worker.v1.ToolDefinition
	(*ToolContext)(nil),       // 5: worker.v1.ToolContext
	(*ToolCall)(nil),          // 6: worker.v1.ToolCall
	(*Attachment)(nil),        // 7: worker.v1.Attachment
	(*TaskRequest)(nil),       // 8: worker.v1.TaskRequest
	(*TaskResponse)(nil),      // 9: worker.v1.TaskResponse
	(*MemoryEntry)(nil),       // 10: worker.v1.MemoryEntry
	(*HeartbeatRequest)(nil),  // 11: worker.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 12: worker.v1.HeartbeatResponse
}
var file_worker_proto_depIdxs = []int32{
	2,  // 0: worker.v1.WorkerMessage.register:type_name -> worker.v1.RegisterWorker
	9,  // 1: worker.v1.WorkerMessage.task_response:type_name -> worker.v1.TaskResponse
	3,  // 2: worker.v1.ServerMessage.register_ack:type_name -> worker.v1.RegisterAck
	8,  // 3: worker.v1.ServerMessage.task_request:type_name -> worker.v1.TaskRequest
	4,  // 4: worker.v1.TaskRequest.tools:type_name -> worker.v1.ToolDefinition
	7,  // 5: worker.v1.TaskRequest.attachments:type_name -> worker.v1.Attachment
	5,  // 6: worker.v1.TaskRequest.tool_context:type_name -> worker.v1.ToolContext
	10, // 7: worker.v1.TaskResponse.new_memories:type_name -> worker.v1.MemoryEntry
	6,  // 8: worker.v1.TaskResponse.tools_called:type_name -> worker.v1.ToolCall
	0,  // 9: worker.v1.WorkerService.TaskStream:input_type -> worker.v1.WorkerMessage
	11, // 10: worker.v1.WorkerService.Heartbeat:input_type -> worker.v1.HeartbeatRequest
	1,  // 11: worker.v1.WorkerService.TaskStream:output_type -> worker.v1.ServerMessage
	12, // 12: worker.v1.WorkerService.Heartbeat:output_type -> worker.v1.HeartbeatResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_TaskResponse)(nil),
	}
	file_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_TaskRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
