// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkerMessage is sent from the worker to the server.
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_TaskResponse
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *RegisterWorker {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResponse() *TaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskResponse); ok {
			return x.TaskResponse
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *RegisterWorker `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_TaskResponse struct {
	TaskResponse *TaskResponse `protobuf:"bytes,2,opt,name=task_response,json=taskResponse,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskResponse) isWorkerMessage_Payload() {}

// ServerMessage is sent from the server to the worker.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_TaskRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetTaskRequest() *TaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TaskRequest); ok {
			return x.TaskRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_TaskRequest struct {
	TaskRequest *TaskRequest `protobuf:"bytes,2,opt,name=task_request,json=taskRequest,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_TaskRequest) isServerMessage_Payload() {}

// RegisterWorker is the first message a worker sends to identify itself.
type RegisterWorker struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	MaxConcurrent      int32                  `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	SupportedProviders []string               `protobuf:"bytes,3,rep,name=supported_providers,json=supportedProviders,proto3" json:"supported_providers,omitempty"` // e.g., ["openai", "anthropic", "ollama"]
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterWorker) Reset() {
	*x = RegisterWorker{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorker) ProtoMessage() {}

func (x *RegisterWorker) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorker.ProtoReflect.Descriptor instead.
func (*RegisterWorker) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWorker) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorker) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *RegisterWorker) GetSupportedProviders() []string {
	if x != nil {
		return x.SupportedProviders
	}
	return nil
}

// RegisterAck is sent by the server to confirm registration.
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TaskRequest is sent from the server to a worker to process a task.
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	UserMessage   string                 `protobuf:"bytes,4,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,5,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`      // Decrypted system prompt
	LlmConfigJson string                 `protobuf:"bytes,6,opt,name=llm_config_json,json=llmConfigJson,proto3" json:"llm_config_json,omitempty"` // JSON: {"provider":"openai","model":"gpt-4o-mini","temperature":0.7,"max_tokens":1024}
	FromJid       string                 `protobuf:"bytes,7,opt,name=from_jid,json=fromJid,proto3" json:"from_jid,omitempty"`
	AgentJid      string                 `protobuf:"bytes,8,opt,name=agent_jid,json=agentJid,proto3" json:"agent_jid,omitempty"`
	AgentName     string                 `protobuf:"bytes,9,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *TaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *TaskRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *TaskRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *TaskRequest) GetLlmConfigJson() string {
	if x != nil {
		return x.LlmConfigJson
	}
	return ""
}

func (x *TaskRequest) GetFromJid() string {
	if x != nil {
		return x.FromJid
	}
	return ""
}

func (x *TaskRequest) GetAgentJid() string {
	if x != nil {
		return x.AgentJid
	}
	return ""
}

func (x *TaskRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

// TaskResponse is sent from the worker back to the server with the LLM result.
type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ResponseText  string                 `protobuf:"bytes,3,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,6,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Non-empty indicates failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResponse) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

func (x *TaskResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *TaskResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TaskResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HeartbeatRequest is a periodic health check from the worker.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,2,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	MemoryUsageMb int32                  `protobuf:"varint,3,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	AvgLatencyMs  int32                  `protobuf:"varint,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsageMb() int32 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *HeartbeatRequest) GetAvgLatencyMs() int32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

// HeartbeatResponse acknowledges the heartbeat.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\tworker.v1\"\x93\x01\n" +
	"\rWorkerMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.worker.v1.RegisterWorkerH\x00R\bregister\x12>\n" +
	"\rtask_response\x18\x02 \x01(\v2\x17.worker.v1.TaskResponseH\x00R\ftaskResponseB\t\n" +
	"\apayload\"\x94\x01\n" +
	"\rServerMessage\x12;\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x16.worker.v1.RegisterAckH\x00R\vregisterAck\x12;\n" +
	"\ftask_request\x18\x02 \x01(\v2\x16.worker.v1.TaskRequestH\x00R\vtaskRequestB\t\n" +
	"\apayload\"\x85\x01\n" +
	"\x0eRegisterWorker\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05R\rmaxConcurrent\x12/\n" +
	"\x13supported_providers\x18\x03 \x03(\tR\x12supportedProviders\"C\n" +
	"\vRegisterAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb2\x02\n" +
	"\vTaskRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12!\n" +
	"\fuser_message\x18\x04 \x01(\tR\vuserMessage\x12#\n" +
	"\rsystem_prompt\x18\x05 \x01(\tR\fsystemPrompt\x12&\n" +
	"\x0fllm_config_json\x18\x06 \x01(\tR\rllmConfigJson\x12\x19\n" +
	"\bfrom_jid\x18\a \x01(\tR\afromJid\x12\x1b\n" +
	"\tagent_jid\x18\b \x01(\tR\bagentJid\x12\x1d\n" +
	"\n" +
	"agent_name\x18\t \x01(\tR\tagentName\"\xf5\x01\n" +
	"\fTaskResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rresponse_text\x18\x03 \x01(\tR\fresponseText\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"model_used\x18\x06 \x01(\tR\tmodelUsed\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\xa0\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\factive_tasks\x18\x02 \x01(\x05R\vactiveTasks\x12&\n" +
	"\x0fmemory_usage_mb\x18\x03 \x01(\x05R\rmemoryUsageMb\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x05R\favgLatencyMs\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x9d\x01\n" +
	"\rWorkerService\x12D\n" +
	"\n" +
	"TaskStream\x12\x18.worker.v1.WorkerMessage\x1a\x18.worker.v1.ServerMessage(\x010\x01\x12F\n" +
	"\tHeartbeat\x12\x1b.worker.v1.HeartbeatRequest\x1a\x1c.worker.v1.HeartbeatResponseB8Z6github.com/aiox-platform/aiox/internal/worker/workerpbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_worker_proto_goTypes = []any{
	(*WorkerMessage)(nil),     // 0: worker.v1.WorkerMessage
	(*ServerMessage)(nil),     // 1: worker.v1.ServerMessage
	(*RegisterWorker)(nil),    // 2: worker.v1.RegisterWorker
	(*RegisterAck)(nil),       // 3: worker.v1.RegisterAck
	(*TaskRequest)(nil),       // 4: worker.v1.TaskRequest
	(*TaskResponse)(nil),      // 5: worker.v1.TaskResponse
	(*HeartbeatRequest)(nil),  // 6: worker.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 7: worker.v1.HeartbeatResponse
}
var file_worker_proto_depIdxs = []int32{
	2, // 0: worker.v1.WorkerMessage.register:type_name -> worker.v1.RegisterWorker
	5, // 1: worker.v1.WorkerMessage.task_response:type_name -> worker.v1.TaskResponse
	3, // 2: worker.v1.ServerMessage.register_ack:type_name -> worker.v1.RegisterAck
	4, // 3: worker.v1.ServerMessage.task_request:type_name -> worker.v1.TaskRequest
	0, // 4: worker.v1.WorkerService.TaskStream:input_type -> worker.v1.WorkerMessage
	6, // 5: worker.v1.WorkerService.Heartbeat:input_type -> worker.v1.HeartbeatRequest
	1, // 6: worker.v1.WorkerService.TaskStream:output_type -> worker.v1.ServerMessage
	7, // 7: worker.v1.WorkerService.Heartbeat:output_type -> worker.v1.HeartbeatResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_TaskResponse)(nil),
	}
	file_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_TaskRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
